[workspace]
members = ["crates/keysmith-core", "src-tauri"]
resolver = "2"

[workspace.package]
version = "2.7.4"
edition = "2024"
license = "Apache-2.0"
authors = ["Sanskar <sanskarin@outlook.in>"]
repository = "https://github.com/sanskarIN/keysmith"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
pedantic = "allow"
nursery = "allow"
unwrap_used = "deny"
expect_used = "deny"
